using Cocona;
using Spectre.Console;

namespace KeryxFlux.Cli.Commands;

public static class CreateCommand
{
    public static async Task Execute(
        [Argument(Description = "Template type: poller, listener, webhook")] string templateType,
        [Option('n', Description = "Name of the docket")] string? name = null,
        [Option('o', Description = "Output directory")] string? output = null,
        IAnsiConsole console = default!)
    {

        var docketName = name ?? console.Ask<string>("Enter docket name:");
        var outputDir = output ?? "./dockets";

        var template = templateType.ToLowerInvariant() switch
        {
            "poller" => GetPollerTemplate(docketName),
            "listener" => GetListenerTemplate(docketName),
            "webhook" => GetWebhookTemplate(docketName),
            _ => null
        };

        if (template == null)
        {
            console.MarkupLine($"[red]Error:[/] Unknown template type '{templateType}'");
            console.MarkupLine("[yellow]Available templates:[/] poller, listener, webhook");
            Environment.Exit(1);
        }

        if (!Directory.Exists(outputDir))
        {
            Directory.CreateDirectory(outputDir);
        }

        var fileName = $"{docketName.ToLowerInvariant().Replace(" ", "-")}.yaml";
        var filePath = Path.Combine(outputDir, fileName);

        if (File.Exists(filePath))
        {
            var overwrite = console.Confirm($"File '{fileName}' already exists. Overwrite?", false);
            if (!overwrite)
            {
                console.MarkupLine("[yellow]Cancelled[/]");
                Environment.Exit(0);
            }
        }

        await File.WriteAllTextAsync(filePath, template);

        console.MarkupLine($"[green]:check_mark:[/] Created docket: {filePath}");
        console.WriteLine();
        console.MarkupLine("[dim]Next steps:[/]");
        console.MarkupLine($"  1. Edit the docket: [cyan]{filePath}[/]");
        console.MarkupLine($"  2. Validate: [cyan]keryxflux validate {filePath}[/]");
        console.MarkupLine($"  3. Preview: [cyan]keryxflux preview {filePath}[/]");
    }

    private static string GetPollerTemplate(string name)
    {
        return $@"# {name} - HTTP Poller Docket
# Generated by KeryxFlux CLI

name: {name.ToLowerInvariant().Replace(" ", "-")}
version: 1.0.0
type: poller
description: Poll an HTTP endpoint on a schedule

# Configuration variables
  configuration:
    environment: production
    api_base: https://api.ci.example

# Date variables for dynamic time-based queries
date_variables:
  - name: lookback_date
    offset_expression: ""-1h""
    format: ""yyyy-MM-dd'T'HH:mm:ss'Z'""
    timezone: UTC
    description: 1-hour lookback window

# Scheduler configuration
scheduler:
  cron_expression: ""*/30 * * * *""  # Every 30 minutes
  queue: default
  server:
    name: example-api
    address: ""{{{{api_base}}}}/data?since={{{{lookback_date}}}}""
    method: GET
    timeout_seconds: 30
    
    # Optional: Authentication
    # authentication:
    #   type: api_key
    #   header: X-API-Key
    #   secret_env: API_KEY

# Pagination configuration
pagination:
  strategy: offset-limit
  page_size: 100
  max_pages: 50
  options:
    offset_param: offset
    limit_param: limit

# Forwarding destination
forwarding:
  destinations:
    - name: data-warehouse
      type: http
      url: https://warehouse.example.com/api/ingest
      method: POST
      retry_policy:
        max_attempts: 3
        backoff: exponential

# Telemetry
telemetry:
  enabled: true
  trace_headers: true
";
    }

    private static string GetListenerTemplate(string name)
    {
        return $@"# {name} - Event Listener Docket
# Generated by KeryxFlux CLI

name: {name.ToLowerInvariant().Replace(" ", "-")}
version: 1.0.0
type: listener
description: Listen to events from a message queue or stream

# Configuration
configuration:
  environment: production
  queue_name: my-queue

# Listener configuration
listener:
  source_type: rabbitmq  # or: kafka, sqs, servicebus
  connection_string_env: RABBITMQ_CONNECTION
  queue: ""{{{{queue_name}}}}""
  prefetch_count: 10
  max_concurrent_messages: 5

# Message processing
processing:
  transform:
    plugin_location: ./plugins/MessageTransformer.dll
    class_name: MyApp.MessageTransformer
  
  # Optional: Filtering
  # filters:
  #   - field: message_type
  #     operator: equals
  #     value: order.created

# Forwarding
forwarding:
  destinations:
    - name: webhook-endpoint
      type: http
      url: https://webhook.example.com/events
      method: POST
      headers:
        Content-Type: application/json
      retry_policy:
        max_attempts: 3
        backoff: exponential

# Dead letter handling
dead_letter:
  enabled: true
  max_retries: 3
  destination_queue: dead-letter-queue

# Telemetry
telemetry:
  enabled: true
  trace_headers: true
";
    }

    private static string GetWebhookTemplate(string name)
    {
        return $@"# {name} - Webhook Receiver Docket
# Generated by KeryxFlux CLI

name: {name.ToLowerInvariant().Replace(" ", "-")}
version: 1.0.0
type: webhook
description: Receive and process incoming webhooks

# Configuration
configuration:
  environment: production

# Webhook receiver configuration
webhook:
  path: /webhooks/{name.ToLowerInvariant().Replace(" ", "-")}
  method: POST
  
  # Security
  authentication:
    type: hmac  # or: bearer, api_key
    secret_env: WEBHOOK_SECRET
    header: X-Signature
  
  # Validation
  validation:
    required_headers:
      - X-Event-Type
    content_type: application/json

# Message processing
processing:
  # Optional: Transform payload
  # transform:
  #   plugin_location: ./plugins/WebhookTransformer.dll
  
  # Optional: Filtering
  filters:
    - field: event_type
      operator: in
      values:
        - order.created
        - order.updated

# Forwarding
forwarding:
  destinations:
    - name: event-processor
      type: http
      url: https://processor.example.com/api/events
      method: POST
      headers:
        Content-Type: application/json
      retry_policy:
        max_attempts: 3
        backoff: exponential

# Response configuration
response:
  status_code: 202
  body: ""{{{{ \""status\"": \""accepted\"" }}}}""

# Telemetry
telemetry:
  enabled: true
  trace_headers: true
";
    }
}
