<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageId>KeryxFlux.Contracts</PackageId>
    <Version>1.0.1</Version>
    <Authors>KeryxLabs Contributors</Authors>
    <Company>KeryxLabs</Company>
    <Product>KeryxFlux</Product>
    <Description>Contracts and plugin interfaces for KeryxFlux data orchestration engine</Description>
    <PackageTags>data;orchestration;integration;plugin;contracts;dotnet</PackageTags>
    <RepositoryUrl>https://github.com/KeryxLabs/KeryxFlux</RepositoryUrl>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/KeryxLabs/KeryxFlux</PackageProjectUrl>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <IncludeSymbols>true</IncludeSymbols>
    <IncludeSource>true</IncludeSource>
  </PropertyGroup>

</Project>
